name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BINARY_FILENAME: "ce-arc-server"
  PACKAGES_DIR: "./server"
  GO_VERSION: "1.25.4"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./server/...

      - name: Build binary
        run: go build -o "${{ env.BINARY_FILENAME }}" "${{ env.PACKAGES_DIR }}"

  deploy:
    needs: build
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step is used to set an image tag variable
      - name: Set image tag version
        id: set-tag
        run: |
          tag="${{ github.sha }}"
          echo "image_tag=${tag:0:8}" >> "$GITHUB_OUTPUT"

      - name: Push container image
        uses: ./.github/actions/publish-container-image
        with:
          registry: ${{ secrets.CT_REGISTRY }}
          image_name: "gh-runner"
          image_tags: "${{ steps.set-tag.outputs.image_tag }}"
          username: ${{ secrets.CT_REGISTRY_USERNAME }}
          password: ${{ secrets.CT_REGISTRY_PASSWORD }}
          context: ./runner
          containerfile: ./runner/runner-ubuntu.containerfile
